name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: DeLaGuardo/setup-clojure@3.6
        with:
          tools-deps: latest

      - name: Build code
        run: bin/build.sh
