name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: DeLaGuardo/setup-clojure@3.6
        with:
          tools-deps: latest

      - name: Lint code
        run: bin/lint.sh
